# Generated by Django 4.0.4 on 2022-05-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetups',
            new_name='Meetup',
        ),
    ]
